### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Bergiu/emojirussell#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Bergiu** [comment]
![2021-08-10_15-15](https://user-images.githubusercontent.com/13796963/128873823-71005995-ce48-4f8f-bfcc-6d339ac8211f.png)
![2021-08-10_15-15_1](https://user-images.githubusercontent.com/13796963/128873828-31f99b34-2fc5-4951-901c-3a8f05e91803.png)


are these screenshots ok? if no what commands should i execute, what should the screenshot show?

As license i've already added MIT.

**Comment by Bergiu** [comment]
features are the same as in [robbyrussel](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#robbyrussell)

i have only changed the dart with emojis

they are now included in the readme

**Comment by unixorn** [comment]
Those are both perfect. I like that you took screen shots with both light and dark backgrounds.

**Comment by Bergiu** [comment]
You're welcome
